# From https://learn.microsoft.com/en-us/dotnet/devops/dotnet-test-github-action
name: Build and test

permissions:
  contents: read

on:
  push:
  pull_request:
    branches: [master]
    paths:
      - "**.cs"
      - "**.csproj"

env:
  DOTNET_VERSION: "6.0.401" # The .NET SDK version to use

jobs:
  build-and-test:
    name: build-and-test-${{matrix.os}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # tag=v4.2.2
        with:
          persist-credentials: "false"

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal
